### PR TITLE
Fix Class Paths

### LINKED ISSUE #10: Emarsys::Contact should be located in app/services/workarea
**Describe the bug**
Emarsys::Contact is not in app/services/workarea folder, therefore when I try to decorate I get a `NameError: uninitialized constant Workarea::Emarsys::Contact`

**To Reproduce**
1. Try to decorate Emarsys::Contact
2. Start up app

**Expected behavior**
App starts up and uses my decorated method

**Workarea Setup:**
 ```
  workarea (= 3.3.35)!
  workarea-ab_testing (= 2.1.0)!
  workarea-afterpay (= 2.1.0)!
  workarea-api (= 4.3.1)!
  workarea-basic_auth (~> 1.0.1)!
  workarea-browse_option (= 2.0.0)!
  workarea-clothing (= 2.1.10)!
  workarea-commerce_cloud (= 1.1.0)!
  workarea-drawer (= 0.1.2)!
  workarea-emarsys (= 1.0.3)!
  workarea-filter_dropdowns (= 3.0.2)!
  workarea-gift_cards (= 3.4.7)!
  workarea-global_e (= 1.1.0)!
  workarea-google_address_autocomplete (= 4.0.1)!
  workarea-google_product_feed (= 3.0.2)!
  workarea-google_tag_manager (= 4.2.6)!
  workarea-hearts (= 3.0.3)!
  workarea-hover_zoom (= 2.0.0)!
  workarea-import (= 3.0.5)!
  workarea-new_relic (= 1.0.1)!
  workarea-oms (= 3.0.0)!
  workarea-paypal (= 2.0.9)!
  workarea-product_grid_content (= 1.2.0)!
  workarea-segmentation (= 2.3.3)!
  workarea-sentry (~> 1.1.1)!
  workarea-share (= 1.2.4)!
  workarea-sitemaps (= 2.1.6)!
  workarea-slick_slider (= 0.1.0)!
  workarea-store_locator (= 4.1.0)!
  workarea-stripe (= 1.0.0.beta.3)!
  workarea-super_hero (= 2.0.5)!
  workarea-upgrade (~> 2.0.7)!
```

### PR DESCRIPTION
**Pull request by tubbo**
Some paths in `app/` did not match their constant names, resulting in
issues when trying to decorate these classes. Move the offending files
to their correct location so as to enable decorating them.

Fixes #10

EMARSYS-3

### CODE REVIEW

**Review by jyucis — APPROVED** [review]

**Review by bavedarnow — APPROVED** [review]

**Comment by tubbo** [comment]
thanks @bavedarnow

**Review by bencrouse — APPROVED** [review]

**Comment by bencrouse** [comment]
@tubbo could you resolve the conflicts here? Also, I'm confused how there would be conflicts if you just renamed some files.

**Review by bencrouse — CHANGES_REQUESTED** [review]
Weirdly conflicting :(

**Comment by tubbo** [comment]
@bencrouse turns out i haven't updated my local master in a minute. should be OK now.

**Pull request merged**
